/*
 * buratinoSettings.h
 *
 * Created: 8/18/2014 11:01:19 AM
 *  Author: val
 */ 


#ifndef BURATINOSETTINGS_H_
#define BURATINOSETTINGS_H_

#define BURATINO_PLATFORM_TEMPERATURE_SENSOR_ONCHIP 0x0
#define BURATINO_PLATFORM_TEMPERATURE_SENSOR_SI7021  0x1

#define BURATINO_CAPABILITY_OCCUPANCY_SENSOR
#define BURATINO_CAPABILITY_TEMPERATURE_SENSOR BURATINO_PLATFORM_TEMPERATURE_SENSOR_ONCHIP


#define BURATINO_SERVER_CLUSTERS_COUNT   4
#define BURATINO_CLIENT_CLUSTERS_COUNT   1

#endif /* BURATINOSETTINGS_H_ */